name: X_v2
description: A Dart package for interacting with Twitter/X API v2.0 and v1.1 endpoints, forked from myConsciousness/twitter-api-v2. With thanks.
version: 1.3.0
homepage: https://github.com/n3w6y/X-v2
license: Apache-2.0

environment:
#  sdk: ">=2.17.0 <3.0.0" # upgraded
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.0.0
  oauth1: ^2.0.0 # Note: Verify Dart 3 compatibility or fork
  universal_io: ^2.2.0
  crypto: ^3.0.5
  collection: ^1.18.0

#original dependencies
#  http: ^0.13.5
#  mime: ^1.0.4
#  oauth1: ^2.0.0
#  universal_io: ^2.2.0
#  freezed_annotation: ^2.2.0
#  json_annotation: ^4.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
  build_runner: ^2.4.0
  mockito: ^5.4.0

# original dev_dependencies:
#  lints: ^2.0.1
#  test: ^1.23.1
#  build_runner: ^2.3.3
#  json_serializable: ^6.6.1
#  freezed: ^2.3.2
#  import_sorter: ^4.6.0
#  mockito: ^5.3.2

#  import_sorter:
#  emojis: true
