name: twitter_api_v2
description: A Dart package for interacting with Twitter/X API v2.0 and v1.1 endpoints, forked from myConsciousness/twitter-api-v2.
version: 1.3.0
homepage: https://github.com/n3w6y/twitter-api-v2
license: Apache-2.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  http: ^1.0.0
  universal_io: ^2.2.2
  crypto: ^3.0.5
  collection: ^1.18.0
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  mime: ^2.0.0
  oauth1: ^2.0.0


dev_dependencies:
  lints: ^3.0.0
  test: ^1.25.7
  build_runner: ^2.4.13
  mockito: ^5.4.4
  freezed: ^2.4.4
  json_serializable: ^6.8.0